server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /gateway
server.error.whitelabel.enabled: false

logging:
  path: logs
  level: DEBUG
  level.com.github.windmill312: DEBUG

spring:
  application:
    name: gateway
  mvc:
    throw-exception-if-no-handler-found: true
  thymeleaf:
    cache: false
    mode: HTML

security:
  token.ttl.seconds: 31536000

gateway:
  web:
    cors:
      allowed-origins:
        - http://127.0.0.1
        - https://127.0.0.1
        - http://127.0.0.1:3000
        - https://127.0.0.1:3000
        - http://127.0.0.1:4000
        - https://127.0.0.1:4000
        - http://127.0.0.1:8080
        - https://127.0.0.1:8080
        - http://localhost
        - https://localhost
        - http://localhost:3000
        - https://localhost:3000
        - http://localhost:4000
        - https://localhost:4000
        - http://localhost:8080
        - https://localhost:8080

  auth:
    credentials:
      service-id: "gateway-service"
      service-secret: "097cdd53-348c-40db-b445-8bcb7299ad35"

  oauth:
    redirect-oauth-uri-template: "http://localhost:4000/oauth/authorize?clientId=%s&redirectUri=%s"

  grpc.client:
    CoffeeHouseServiceV1Grpc:
      host: localhost
      port: 8081
    ProductServiceV1Grpc:
      host: localhost
      port: 8082
    OrderServiceV1Grpc:
      host: localhost
      port: 8083
    AuthServiceV1Grpc:
      host: localhost
      port: 8085
    OAuthServiceV1Grpc:
      host: localhost
      port: 8085
    CredentialsServiceV1Grpc:
      host: localhost
      port: 8085
    PrincipalServiceV1Grpc:
      host: localhost
      port: 8085