server:
  address: 0.0.0.0
  port: port: ${PORT:8080}
  servlet:
    context-path: /gateway
server.error.whitelabel.enabled: false

logging:
  path: logs
  level: DEBUG
  level.com.sychev: DEBUG

spring:
  application:
    name: gateway
  mvc:
    throw-exception-if-no-handler-found: true
  thymeleaf:
    cache: false
    mode: HTML
    enabled: false

gateway:
  web:
    cors:
      allowed-origins:
        - http://127.0.0.1
        - https://127.0.0.1
        - http://127.0.0.1:3000
        - https://127.0.0.1:3000
        - http://127.0.0.1:4000
        - https://127.0.0.1:4000
        - http://127.0.0.1:8080
        - https://127.0.0.1:8080
        - http://localhost
        - https://localhost
        - http://localhost:3000
        - https://localhost:3000
        - http://localhost:4000
        - https://localhost:4000
        - http://localhost:8080
        - https://localhost:8080

  grpc.client:
    CoffeeHouseServiceV1Grpc:
      host: https://coffee-house-api.herokuapp.com/
      port: 8081
    ProductServiceV1Grpc:
      host: localhost
      port: 8082
    OrderServiceV1Grpc:
      host: localhost
      port: 8083